build:
  environment:
    php:
      version: 8.1 # Default PHP version
  nodes:
    node_8.1:
      environment:
        php:
          version: 8.1
    node_8.2:
      environment:
        php:
          version: 8.2
    node_8.3:
      environment:
        php:
          version: 8.3
    node_8.4:
      environment:
        php:
          version: 8.4
  tests:
    override:
      - command: phpunit
